name=RohitCore-Power
version=1.0.0
author=Rohit Maji
maintainer=Rohit Maji <rohitmaji2002@gmail.com>
sentence=Battery and voltage monitoring library for Arduino
paragraph=Provides voltage measurement, battery percentage estimation, and low battery detection.
category=Signal Input/Output
url=https://github.com/rohitmaji004/RohitCore-Power
architectures=*
depends=RohitCore-Base
